language: node_js

sudo: false

node_js:
  - "8"

install:
    - npm install

jobs:
  include:
#    - stage: lint
#      script: npm run lint
#    - stage: test
#      script: npm run test
    - stage: build
      script: npm run build -- --environment prod --base-href "/modis-mojito-familink-front/"

deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  local_dir: dist
  on:
    branch: develop
